#	UGR Transparente. Sitio Web de la Universidad de Granada de acceso a Datos Abiertos.
#	Copyright (C) 2015 Juan Julián Merelo Guervós, Germán Martínez Maldonado
#
#	This file is part of UGR Transparente.
#
#	UGR Transparente is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	UGR Transparente is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program. If not, see <http://www.gnu.org/licenses/>.


# Languaje de la aplicación
language: node_js

# Versiones con las que correr los tests
node_js:
  - 6.1.0
  - 4.4.3
  - 4.2.6

sudo: false

# Descargar contenido estático y ejecutar servidor X virtual
before_script:
  - ./getRecursos.sh
  - sleep 2
script:
  - npm test
  - npm run jshint
#  - npm run zombie_test

# Coveralls coverage
after_success:
    - npm run coveralls
