#	UGR Transparente. Sitio Web de la Universidad de Granada de acceso a Datos Abiertos.
#	Copyright (C) 2015 Juan Julián Merelo Guervós, Germán Martínez Maldonado
#
#	This file is part of UGR Transparente.
#
#	UGR Transparente is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	UGR Transparente is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program. If not, see <http://www.gnu.org/licenses/>.


# Languaje de la aplicación
language: node_js

# Versiones con las que correr los tests
node_js:
  - "stable"
  - "5.5.0"
  - "4.2.6"
  - "0.12"

sudo: false

addons:
  apt:
    packages:
    - unzip

# Descargar contenido estátco
before_install:
  - "./installChromedriverTravis.sh"
  - "./getRecursos.sh"

# Coveralls coverage
after_success:
    - npm run coveralls
